const canvas=document.getElementById('preview');const ctx=canvas.getContext('2d');const deletePin=document.getElementById('deleteWord');let animLast=performance.now();
const state={mode:'edit',res:'96x128',background:{kind:'solid',color:'#000',image:null},lines:[{words:[{text:'Hello',color:'#FFF'}],align:'center'}],sel:{line:0,word:0},lineGap:2,wordSpacing:8,preventCutoff:true,anim:{pulse:{on:false,amount:.4},flicker:{on:false,intensity:.2},scroll:{on:false,speed:1.5,offset:0}}};
function buildThumbs(){const t=document.getElementById('thumbs');t.innerHTML='';const list=[];if(state.res==='96x128'){list.push('Preset_A','Preset_B');}else{list.push('Preset_C','Preset_D');}list.push('Solid','Upload');list.forEach(n=>{const d=document.createElement('div');d.className='thumb';let url=`assets/thumbs/${n}_thumb.png`;if(n==='Solid')url='assets/thumbs/Solid_thumb.png';if(n==='Upload')url='assets/thumbs/Upload_thumb.png';d.style.backgroundImage=`url("${url}")`;d.title=n;d.onclick=()=>{if(n==='Solid'){state.background={kind:'solid',color:'#000'};render();}else if(n==='Upload'){const i=document.createElement('input');i.type='file';i.accept='image/*';i.onchange=e=>{const file=e.target.files[0];const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{state.background={kind:'image',image:img};render();};img.src=r.result;};r.readAsDataURL(file);};i.click();}else{const img=new Image();const sub=(state.res==='96x128')?'96x128':'64x64';img.onload=()=>{state.background={kind:'image',image:img};render();};img.src=`assets/presets/${sub}/${n}.png`;}};t.appendChild(d);});}
buildThumbs();
document.getElementById('resolution').onchange=(e)=>{state.res=e.target.value;if(state.res==='96x128'){canvas.width=384;canvas.height=512;}else{canvas.width=512;canvas.height=512;}render();buildThumbs();};
function fontFor(){return 'bold 22px Monospace';}
function measure(w){ctx.font=fontFor();const m=ctx.measureText(w.text||'');return Math.ceil(m.width);}
function render(){ctx.clearRect(0,0,canvas.width,canvas.height); if(state.background.kind==='image'&&state.background.image){const img=state.background.image;const s=Math.max(canvas.width/img.width,canvas.height/img.height);const w=img.width*s,h=img.height*s;ctx.drawImage(img,(canvas.width-w)/2,(canvas.height-h)/2,w,h);}else{ctx.fillStyle=state.background.color;ctx.fillRect(0,0,canvas.width,canvas.height);}state.lines.forEach((line,li)=>{ctx.font=fontFor();ctx.textBaseline='top';let xStart=10;const sizes=line.words.map(measure);const total=sizes.reduce((a,b)=>a+b,0)+(sizes.length-1)*state.wordSpacing;if(line.align==='center')xStart=(canvas.width-total)/2;if(line.align==='right')xStart=canvas.width-total-10;let x=xStart;const y=20+li*(26+state.lineGap*2);line.words.forEach((w,wi)=>{const ww=sizes[wi];ctx.fillStyle=w.color||'#fff';if(state.anim.scroll.on){x-=state.anim.scroll.offset;}const drawX=Math.max(6,Math.min(x,canvas.width-ww-6));ctx.fillText(w.text,drawX,y); if(li===state.sel.line&&wi===state.sel.word){drawSel(drawX,y,ww,26);} x+=ww+state.wordSpacing;});});}
function drawSel(x,y,w,h){const rect=canvas.getBoundingClientRect();let box=document.querySelector('.selectedBox');if(!box){box=document.createElement('div');box.className='selectedBox';canvas.parentElement.appendChild(box);}box.style.display='block';box.style.left=(rect.left+x)+'px';box.style.top=(rect.top+y)+'px';box.style.width=w+'px';box.style.height=h+'px';deletePin.style.display='block';deletePin.style.left=(rect.left+x+w+8)+'px';deletePin.style.top=(rect.top+y-24)+'px';deletePin.onclick=()=>{state.lines[state.sel.line].words.splice(state.sel.word,1);deletePin.style.display='none';render();};}
function hit(x,y){for(let li=0;li<state.lines.length;li++){const line=state.lines[li];let xStart=10;const sizes=line.words.map(measure);const total=sizes.reduce((a,b)=>a+b,0)+(sizes.length-1)*state.wordSpacing;if(line.align==='center')xStart=(canvas.width-total)/2;if(line.align==='right')xStart=canvas.width-total-10;let cx=xStart;const yy=20+li*(26+state.lineGap*2);for(let wi=0;wi<line.words.length;wi++){const w=sizes[wi];if(x>=cx && x<=cx+w && y>=yy && y<=yy+26){return {line:li,word:wi};}cx+=w+state.wordSpacing;}}return null;}
canvas.addEventListener('mousedown', (e)=>{const r=canvas.getBoundingClientRect();const x=e.clientX-r.left,y=e.clientY-r.top;const h=hit(x,y);if(h){state.sel=h;render();}else{state.sel={line:state.sel.line||0,word:-1};render();}});
document.getElementById('btnClear').onclick=()=>{state.lines=[{words:[],align:'center'}];state.sel={line:0,word:-1};render();};
document.querySelectorAll('.pill').forEach(b=>b.onclick=()=>{document.querySelectorAll('.panel').forEach(p=>p.style.display='none');document.getElementById('panel-'+b.dataset.panel).style.display='flex';});
document.querySelectorAll('.alignBtn').forEach(b=>b.onclick=()=>{state.lines[state.sel.line].align=b.dataset.align;render();});
document.getElementById('resetAlign').onclick=()=>{state.lines[state.sel.line].align='center';render();};
document.getElementById('lineGap').oninput=(e)=>{state.lineGap=parseInt(e.target.value||'2');render();};
document.getElementById('wordSpacing').oninput=(e)=>{state.wordSpacing=parseInt(e.target.value||'8');render();};
document.getElementById('preventCutoff').onchange=(e)=>{state.preventCutoff=e.target.checked;render();};
const SW=['#00b4ff','#22d366','#ffd43b','#ff4dd2','#ff4747','#ffffff','#000000'];const sw=document.getElementById('swatches');SW.forEach(c=>{const d=document.createElement('div');d.className='sw';d.style.background=c;d.onclick=()=>{const sel=state.lines[state.sel.line];const w=sel.words[state.sel.word];if(!w) return;w.color=c;render();};sw.appendChild(d);});document.getElementById('colorPicker').oninput=(e)=>{const sel=state.lines[state.sel.line];const w=sel.words[state.sel.word];if(!w)return;w.color=e.target.value;render();};
function tick(ts){const dt=(ts-animLast)/1000;animLast=ts;if(state.anim.scroll.on){state.anim.scroll.offset += state.anim.scroll.speed*dt*20;}render();requestAnimationFrame(tick);}requestAnimationFrame(tick);
render();